services:
  - type: web
    name: wikihunt-backend
    runtime: node
    rootDir: backend          # apunta al subdirectorio
    buildCommand: npm install && npm run build
    startCommand: npm run start
    plan: free
    healthCheckPath: /health
